services:
  app:
    image: disease_predictor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output